# Development overrides. Shared settings come from application.properties.
webforj.debug = true
webforj.devtools.craftforj.enabled=true
webforj.devtools.livereload.enabled=true
webforj.devtools.livereload.static-resources-enabled=true
webforj.devtools.browser.open=true

server.shutdown=immediate
