# This configuration file is in HOCON format:
# https://github.com/lightbend/config/blob/master/HOCON.md

webforj.entry = ${package}.Application
webforj.quiet=on
webforj.debug = true
webforj.devtools.craftforj.enabled=true
webforj.devtools.livereload.enabled = true
